# Generated by Django 4.2.6 on 2023-10-23 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_name', models.CharField(choices=[('fulltime_contract', 'Full-time/Contract'), ('fulltime_permanent', 'Full-time/Permanent'), ('parttime_contract', 'Part-time/Contract'), ('parttime_permanent', 'Part-time/Permanent')], default='fulltime_contract', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('language', models.CharField(choices=[('Indonesia', 'INDONESIA'), ('English', 'ENGLISH')], default='ID', max_length=20)),
                ('proficiency', models.CharField(choices=[('native', 'Native'), ('expert', 'Expert'), ('fluent', 'Fluent'), ('intermediate', 'Intermediate'), ('beginner', 'Beginner')], default='native', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('short_intro', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, max_length=1000, null=True)),
                ('profile_picture', models.ImageField(default='profile/user-default.png', null=True, upload_to='profile/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_total', models.IntegerField(blank=True, default=0, null=True)),
                ('rate_ratio', models.FloatField(blank=True, default=0, null=True)),
                ('employment_type', models.ManyToManyField(blank=True, to='userApi.employmenttype')),
                ('languages', models.ManyToManyField(blank=True, to='userApi.language')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('skill_name', models.CharField(blank=True, max_length=20, null=True)),
                ('skill_level', models.CharField(choices=[('novice', 'Novice'), ('beginner', 'Beginner'), ('advance_beginner', 'Advanced Beginner'), ('competent', 'Competent'), ('proficient', 'Proficient'), ('expert', 'Expert')], default='novice', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_name', models.CharField(choices=[('personal', 'Personal'), ('company', 'Company')], default='personal', max_length=20)),
                ('user', models.OneToOneField(default='Personal', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rate_value', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_rating', to='userApi.profile')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userApi.profile')),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='rating_received',
            field=models.ManyToManyField(related_name='rated_profiles', through='userApi.UserRate', to='userApi.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='userApi.skills'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('details', models.TextField(blank=True, max_length=600, null=True)),
                ('total_exp', models.FloatField()),
                ('user', models.ForeignKey(default='Personal', on_delete=django.db.models.deletion.CASCADE, to='userApi.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ExpectedSalary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('rp', 'RP'), ('usd', 'USD')], default='rp', max_length=3)),
                ('nominal', models.FloatField()),
                ('paid_period', models.CharField(choices=[('hourly', 'Hourly'), ('monthly', 'Honthly'), ('yearly', 'Yearly')], default='hourly', max_length=20)),
                ('user', models.OneToOneField(default='Personal', on_delete=django.db.models.deletion.CASCADE, to='userApi.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('major', models.CharField(blank=True, max_length=50, null=True)),
                ('degrees', models.CharField(choices=[('diploma', 'Diploma'), ('bachelor', 'Bachelor'), ('postgraduate', 'Postgraduate')], default='diploma', max_length=20)),
                ('school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
                ('user', models.ForeignKey(default='Personal', on_delete=django.db.models.deletion.CASCADE, to='userApi.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('portfolio_link', models.CharField(max_length=100)),
                ('portfolio_name', models.CharField(choices=[('github', 'Github'), ('linkedin', 'LinkedIn'), ('personal_website', 'Personal Website'), ('other_link', 'Other Link')], default=1, max_length=20)),
                ('user', models.ForeignKey(default='Personal', on_delete=django.db.models.deletion.CASCADE, to='userApi.profile')),
            ],
            options={
                'unique_together': {('user', 'portfolio_name')},
            },
        ),
        migrations.CreateModel(
            name='Networking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('networking_link', models.CharField(max_length=100)),
                ('networking_name', models.CharField(choices=[(1, 'LinkedIn'), (2, 'Facebook'), (3, 'Instagram'), (4, 'Twitter')], default=1, max_length=20)),
                ('user', models.ForeignKey(default='Personal', on_delete=django.db.models.deletion.CASCADE, to='userApi.profile')),
            ],
            options={
                'unique_together': {('user', 'networking_name')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False, null=True)),
                ('date_read', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='userApi.profile')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userApi.profile')),
            ],
            options={
                'ordering': ['is_read', '-created'],
                'unique_together': {('sender', 'recipient')},
            },
        ),
    ]
