# Generated by Django 4.2.6 on 2023-10-19 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('short_intro', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, max_length=1000, null=True)),
                ('profile_picture', models.ImageField(default='profile/user-default.png', null=True, upload_to='profile/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_name', models.IntegerField(choices=[('personal', 'Personal'), ('company', 'Company')], default='personal')),
                ('user', models.OneToOneField(default='Personal', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rate_total', models.IntegerField(blank=True, default=0, null=True)),
                ('rate_ratio', models.FloatField(blank=True, default=0, null=True)),
                ('rated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('skill_name', models.CharField(blank=True, max_length=20, null=True)),
                ('skill_level', models.IntegerField(choices=[('novice', 'Novice'), ('beginner', 'Beginner'), ('advance_beginner', 'Advanced Beginner'), ('competent', 'Competent'), ('proficient', 'Proficient'), ('expert', 'Expert')], default='novice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userApi.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False, null=True)),
                ('date_read', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='userApi.profile')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userApi.profile')),
            ],
            options={
                'ordering': ['is_read', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('details', models.TextField(blank=True, max_length=600, null=True)),
                ('total_exp', models.FloatField()),
                ('user', models.ForeignKey(default='Personal', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpectedSalary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.IntegerField(choices=[('rp', 'RP'), ('usd', 'USD')], default='rp')),
                ('nominal', models.FloatField()),
                ('paid_period', models.IntegerField(choices=[('hourly', 'Hourly'), ('monthly', 'Honthly'), ('yearly', 'Yearly')], default='hourly')),
                ('user', models.OneToOneField(default='Personal', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('major', models.CharField(blank=True, max_length=50, null=True)),
                ('degrees', models.IntegerField(choices=[('diploma', 'Diploma'), ('bachelor', 'Bachelor'), ('postgraduate', 'Postgraduate')], default='diploma')),
                ('school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
                ('user', models.ForeignKey(default='Personal', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('portfolio_link', models.CharField(max_length=100)),
                ('portfolio_name', models.IntegerField(choices=[(1, 'Github'), (2, 'LinkedIn'), (3, 'Personal Website'), (4, 'Other Link')], default=1)),
                ('user', models.ForeignKey(default='Personal', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'portfolio_name')},
            },
        ),
        migrations.CreateModel(
            name='Networking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('networking_link', models.CharField(max_length=100)),
                ('networking_name', models.IntegerField(choices=[(1, 'LinkedIn'), (2, 'Facebook'), (3, 'Instagram'), (4, 'Twitter')], default=1)),
                ('user', models.ForeignKey(default='Personal', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'networking_name')},
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('language', models.CharField(choices=[('ID', 'INDONESIA'), ('EN', 'ENGLISH')], default='ID', max_length=2)),
                ('proficiency', models.IntegerField(choices=[('native', 'Native'), ('expert', 'Expert'), ('fluent', 'Fluent'), ('intermediate', 'Intermediate'), ('beginner', 'Beginner')], default='native')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApi.profile')),
            ],
            options={
                'unique_together': {('user', 'language')},
            },
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type_name', models.IntegerField(choices=[('fulltime_contract', 'Full-time/Contract'), ('fulltime_permanent', 'Full-time/Permanent'), ('parttime_contract', 'Part-time/Contract'), ('parttime_permanent', 'Part-time/Permanent')], default='fulltime_contract')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userApi.profile')),
            ],
            options={
                'unique_together': {('user', 'type_name')},
            },
        ),
    ]
