# Generated by Django 4.2.6 on 2023-10-20 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degrees',
            field=models.CharField(choices=[('diploma', 'Diploma'), ('bachelor', 'Bachelor'), ('postgraduate', 'Postgraduate')], default='diploma', max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='user',
            field=models.ForeignKey(default='Personal', on_delete=django.db.models.deletion.CASCADE, to='userApi.profile'),
        ),
        migrations.AlterField(
            model_name='employmenttype',
            name='type_name',
            field=models.CharField(choices=[('fulltime_contract', 'Full-time/Contract'), ('fulltime_permanent', 'Full-time/Permanent'), ('parttime_contract', 'Part-time/Contract'), ('parttime_permanent', 'Part-time/Permanent')], default='fulltime_contract', max_length=50),
        ),
        migrations.AlterField(
            model_name='expectedsalary',
            name='currency',
            field=models.CharField(choices=[('rp', 'RP'), ('usd', 'USD')], default='rp', max_length=3),
        ),
        migrations.AlterField(
            model_name='expectedsalary',
            name='paid_period',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('monthly', 'Honthly'), ('yearly', 'Yearly')], default='hourly', max_length=20),
        ),
        migrations.AlterField(
            model_name='expectedsalary',
            name='user',
            field=models.OneToOneField(default='Personal', on_delete=django.db.models.deletion.CASCADE, to='userApi.profile'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(default='Personal', on_delete=django.db.models.deletion.CASCADE, to='userApi.profile'),
        ),
        migrations.AlterField(
            model_name='language',
            name='proficiency',
            field=models.CharField(choices=[('native', 'Native'), ('expert', 'Expert'), ('fluent', 'Fluent'), ('intermediate', 'Intermediate'), ('beginner', 'Beginner')], default='native', max_length=20),
        ),
        migrations.AlterField(
            model_name='networking',
            name='networking_name',
            field=models.CharField(choices=[(1, 'LinkedIn'), (2, 'Facebook'), (3, 'Instagram'), (4, 'Twitter')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='networking',
            name='user',
            field=models.ForeignKey(default='Personal', on_delete=django.db.models.deletion.CASCADE, to='userApi.profile'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(choices=[('github', 'Github'), ('linkedin', 'LinkedIn'), ('personal_website', 'Personal Website'), ('other_link', 'Other Link')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(default='Personal', on_delete=django.db.models.deletion.CASCADE, to='userApi.profile'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_level',
            field=models.CharField(choices=[('novice', 'Novice'), ('beginner', 'Beginner'), ('advance_beginner', 'Advanced Beginner'), ('competent', 'Competent'), ('proficient', 'Proficient'), ('expert', 'Expert')], default='novice', max_length=50),
        ),
        migrations.AlterField(
            model_name='userrate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_owner', to='userApi.profile'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='type_name',
            field=models.CharField(choices=[('personal', 'Personal'), ('company', 'Company')], default='personal', max_length=20),
        ),
    ]
