# Generated by Django 4.2.6 on 2023-10-20 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0002_alter_education_degrees_alter_education_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('sender', 'recipient')},
        ),
    ]
