# Generated by Django 4.2.6 on 2023-10-20 03:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userApi', '0002_alter_education_degrees_alter_education_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosted',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('job_title', models.CharField(max_length=50)),
                ('job_status', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='close', max_length=10)),
                ('job_location', models.CharField(blank=True, max_length=50, null=True)),
                ('job_salary', models.FloatField()),
                ('job_type', models.CharField(choices=[('fulltime_contract', 'Full-time/Contract'), ('fulltime_permanent', 'Full-time/Permanent'), ('parttime_contract', 'Part-time/Contract'), ('parttime_permanent', 'Part-time/Permanent')], default='fulltime_permanent', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_detail', models.TextField(max_length=500)),
                ('experience_level', models.CharField(choices=[('entry_level', 'Entry Level'), ('junior_level', 'Junior Level'), ('intermediate', 'Intermediate'), ('middle', 'Middle Level'), ('senior', 'Senior Level')], default='entry_level', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userApi.profile')),
            ],
        ),
        migrations.CreateModel(
            name='JobInterested',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobApi.jobposted')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userApi.profile')),
            ],
        ),
    ]
